const express = require('express');
const OpenAI = require('openai');
const path = require('path');
const crypto = require('crypto');
const QuizQuestion = require('../models/QuizQuestion');
const router = express.Router();
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const DEFAULT_GROQ_MODEL = process.env.GROQ_MODEL || 'llama-3.3-70b-versatile';
const FALLBACK_GROQ_MODEL = process.env.GROQ_FALLBACK_MODEL || 'llama-3.1-8b-instant';

// Helper function to get Groq client with lazy initialization
const getGroqClient = () => {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error('GROQ_API_KEY is not set in environment variables');
  }
  return new OpenAI({
    apiKey: apiKey,
    baseURL: "https://api.groq.com/openai/v1",
  });
};

const runChatCompletion = async (openai, payload, model = DEFAULT_GROQ_MODEL) => {
  try {
    return await openai.chat.completions.create({ ...payload, model });
  } catch (err) {
    if (err?.code === 'model_decommissioned' && model !== FALLBACK_GROQ_MODEL) {
      console.warn(`⚠️ Model ${model} is decommissioned. Retrying with ${FALLBACK_GROQ_MODEL}.`);
      return openai.chat.completions.create({ ...payload, model: FALLBACK_GROQ_MODEL });
    }
    throw err;
  }
};

const normalizeText = (value = '') => {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
};

const buildQuestionHash = (question) => {
  return crypto.createHash('sha256').update(normalizeText(question)).digest('hex');
};

const normalizeDifficulty = (value) => {
  const difficulty = String(value || 'beginner').toLowerCase().trim();
  if (difficulty === 'easy' || difficulty === 'beginner') return 'beginner';
  if (difficulty === 'medium') return 'medium';
  if (difficulty === 'hard' || difficulty === 'advanced') return 'hard';
  return 'beginner';
};

const generateQuizQuestionWithAI = async (openai, { topic, difficulty, excludedQuestions = [] }) => {
  const levelGuide = {
    beginner: 'Beginner: fundamentals, basic syntax, simple reasoning.',
    medium: 'Medium: applied concepts, moderate reasoning, real interview style.',
    hard: 'Hard: advanced concepts, edge cases, deeper interview challenge.',
  };

  const exclusionNote = excludedQuestions.length
    ? `Do NOT generate any of these existing questions or close paraphrases:\n- ${excludedQuestions.join('\n- ')}`
    : 'Avoid previously common boilerplate questions and generate a fresh, realistic one.';

  const jsonPrompt = `
Generate ONE frequently asked interview MCQ.

Topic: ${topic}
Difficulty: ${difficulty}
Difficulty guide: ${levelGuide[difficulty]}

Rules:
1) It must be a real-world commonly asked interview question.
2) Keep options distinct and plausible.
3) Exactly 4 options.
4) correctIndex must be 0, 1, 2, or 3.
5) explanation must be concise and accurate.
6) ${exclusionNote}

Return ONLY valid JSON in this exact shape:
{
  "question": "string",
  "options": ["string", "string", "string", "string"],
  "correctIndex": 0,
  "explanation": "string",
  "isFrequentlyAsked": true
}
`;

  const completion = await runChatCompletion(openai, {
    messages: [{ role: 'user', content: jsonPrompt }],
    temperature: 0.4,
    response_format: { type: 'json_object' },
  });

  const content = completion.choices[0]?.message?.content;
  const parsed = JSON.parse(content);

  if (!parsed?.question || !Array.isArray(parsed?.options) || parsed.options.length !== 4) {
    throw new Error('Invalid quiz format generated by model.');
  }

  return {
    question: String(parsed.question).trim(),
    options: parsed.options.map((option) => String(option).trim()),
    correctIndex: Number(parsed.correctIndex),
    explanation: String(parsed.explanation || '').trim() || 'Explanation not provided.',
    isFrequentlyAsked: parsed.isFrequentlyAsked !== false,
  };
};

// --- 1. CHAT ENDPOINT ---
router.post('/chat', async (req, res) => {
  try {
    const { messages, systemPrompt } = req.body;
    const openai = getGroqClient();

    // --- CRITICAL FIX ---
    // We must pass the PREVIOUS conversation history to the model.
    // If we only pass the last message, the AI forgets everything.
    const conversation = [
        { role: "system", content: systemPrompt }, 
        ...messages // <--- This spreads the entire history into the prompt
    ];

    const completion = await runChatCompletion(openai, {
      messages: conversation,
      temperature: 0.7, // Lower temperature = less random / less repetition
    });

    res.json({ result: completion.choices[0]?.message?.content });

  } catch (err) {
    console.error("AI Error:", err);
    res.status(500).json({ error: "AI Failed" });
  }
});

// --- 2. QUIZ ENDPOINT ---
router.post('/quiz', async (req, res) => {
  try {
    const { prompt } = req.body;
    const openai = getGroqClient();

    // Llama-3 instruction to force JSON
    const jsonPrompt = `
      ${prompt}
      
      IMPORTANT: Return ONLY valid JSON. Do not add markdown formatting like \`\`\`json.
      Structure:
      {
        "question": "string",
        "options": ["string", "string", "string", "string"],
        "correctIndex": number,
        "explanation": "string"
      }
    `;

    const completion = await runChatCompletion(openai, {
      messages: [{ role: "user", content: jsonPrompt }],
      temperature: 0.7,
      response_format: { type: "json_object" } // Force JSON mode
    });

    const content = completion.choices[0]?.message?.content;
    
    // Parse it safely
    const quizData = JSON.parse(content);
    res.json(quizData);

  } catch (err) {
    console.error("Quiz Gen Error:", err);
    res.status(500).json({ error: "Quiz Gen Failed" });
  }
});

// --- 3. DYNAMIC QUIZ ENDPOINT (Difficulty + No Repeat Across Users) ---
router.post('/quiz-question', async (req, res) => {
  try {
    const openai = getGroqClient();
    const topicInput = req.body?.topic || req.body?.category || 'General Aptitude';
    const difficultyInput = req.body?.difficulty || req.body?.level || 'beginner';
    const userId = req.body?.userId ? String(req.body.userId) : null;

    const topic = String(topicInput).trim();
    const topicKey = topic.toLowerCase();
    const difficulty = normalizeDifficulty(difficultyInput);

    let selectedQuestion = await QuizQuestion.findOne({
      topic: topicKey,
      difficulty,
      timesServed: 0,
    }).sort({ isFrequentlyAsked: -1, createdAt: 1 });

    if (!selectedQuestion) {
      const existing = await QuizQuestion.find({ topic: topicKey, difficulty })
        .select('question questionHash')
        .lean();
      const existingHashes = new Set(existing.map((item) => item.questionHash));
      const excludedQuestions = existing.map((item) => item.question).slice(0, 25);

      for (let attempt = 0; attempt < 6; attempt += 1) {
        const generated = await generateQuizQuestionWithAI(openai, {
          topic,
          difficulty,
          excludedQuestions,
        });

        const hash = buildQuestionHash(generated.question);
        if (existingHashes.has(hash)) {
          continue;
        }

        try {
          selectedQuestion = await QuizQuestion.create({
            question: generated.question,
            questionHash: hash,
            options: generated.options,
            correctIndex: generated.correctIndex,
            explanation: generated.explanation,
            topic: topicKey,
            difficulty,
            isFrequentlyAsked: generated.isFrequentlyAsked,
            source: 'ai',
          });
          break;
        } catch (createError) {
          if (createError?.code === 11000) {
            continue;
          }
          throw createError;
        }
      }
    }

    if (!selectedQuestion) {
      return res.status(409).json({
        error: 'No unique question available for this topic and difficulty. Try a different difficulty.',
      });
    }

    selectedQuestion.timesServed += 1;
    selectedQuestion.lastServedAt = new Date();
    if (userId && !selectedQuestion.servedToUsers.includes(userId)) {
      selectedQuestion.servedToUsers.push(userId);
    }
    await selectedQuestion.save();

    res.json({
      _id: selectedQuestion._id,
      question: selectedQuestion.question,
      options: selectedQuestion.options,
      correctIndex: selectedQuestion.correctIndex,
      explanation: selectedQuestion.explanation,
      topic: selectedQuestion.topic,
      difficulty: selectedQuestion.difficulty,
      isHighFrequency: selectedQuestion.isFrequentlyAsked,
      noRepeatPolicy: 'global',
    });
  } catch (err) {
    console.error('Dynamic Quiz Error:', err);
    res.status(500).json({ error: 'Failed to generate dynamic quiz question.' });
  }
});

// --- 4. RESUME UPLOAD ROUTE ---
const { protect } = require('../middleware/authMiddleware');
const upload = require('../middleware/uploadMiddleware');
const aiController = require('../controllers/aiControllers');

router.post('/upload-resume', protect, upload.single('resume'), aiController.uploadResume);

module.exports = router;